package com.ritchey.choices.domain.chapel;

import java.io.Serializable;
import java.util.Date;

public class Leaders implements Reflect, Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leaders.id
     *
     * @mbggenerated Thu Jan 14 11:34:00 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leaders.label
     *
     * @mbggenerated Thu Jan 14 11:34:00 CST 2021
     */
    private String label;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leaders.endTerm
     *
     * @mbggenerated Thu Jan 14 11:34:00 CST 2021
     */
    private Date endterm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leaders.active
     *
     * @mbggenerated Thu Jan 14 11:34:00 CST 2021
     */
    private Boolean active;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table leaders
     *
     * @mbggenerated Thu Jan 14 11:34:00 CST 2021
     */
    private static final long serialVersionUID = 20210114113400L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leaders.id
     *
     * @return the value of leaders.id
     *
     * @mbggenerated Thu Jan 14 11:34:00 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leaders.id
     *
     * @param id the value for leaders.id
     *
     * @mbggenerated Thu Jan 14 11:34:00 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leaders.label
     *
     * @return the value of leaders.label
     *
     * @mbggenerated Thu Jan 14 11:34:00 CST 2021
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leaders.label
     *
     * @param label the value for leaders.label
     *
     * @mbggenerated Thu Jan 14 11:34:00 CST 2021
     */
    public void setLabel(String label) {
        this.label = label == null ? null : label.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leaders.endTerm
     *
     * @return the value of leaders.endTerm
     *
     * @mbggenerated Thu Jan 14 11:34:00 CST 2021
     */
    public Date getEndterm() {
        return endterm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leaders.endTerm
     *
     * @param endterm the value for leaders.endTerm
     *
     * @mbggenerated Thu Jan 14 11:34:00 CST 2021
     */
    public void setEndterm(Date endterm) {
        this.endterm = endterm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leaders.active
     *
     * @return the value of leaders.active
     *
     * @mbggenerated Thu Jan 14 11:34:00 CST 2021
     */
    public Boolean getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leaders.active
     *
     * @param active the value for leaders.active
     *
     * @mbggenerated Thu Jan 14 11:34:00 CST 2021
     */
    public void setActive(Boolean active) {
        this.active = active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leaders
     *
     * @mbggenerated Thu Jan 14 11:34:00 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getName());
        sb.append("[");
        sb.append("Hash = ").append(hashCode());
        sb.append(",id=").append(id);
        sb.append(",label=").append(label);
        sb.append(",endterm=").append(endterm);
        sb.append(",active=").append(active);
        sb.append(",serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leaders
     *
     * @mbggenerated Thu Jan 14 11:34:00 CST 2021
     */
    @Override
    public Object get(String name) {
        if (name.equals("id")) return id;
        if (name.equals("label")) return label;
        if (name.equals("endterm")) return endterm;
        if (name.equals("active")) return active;
        return null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leaders
     *
     * @mbggenerated Thu Jan 14 11:34:00 CST 2021
     */
    @Override
    public void set(String name, Object value) {
        if (name.equals("id")) id = value==null?null:(java.lang.Integer) value;
        if (name.equals("label")) label = value==null?null:(java.lang.String) value;
        if (name.equals("endterm")) endterm = value==null?null:(java.util.Date) value;
        if (name.equals("active")) active = value==null?null:(java.lang.Boolean) value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leaders
     *
     * @mbggenerated Thu Jan 14 11:34:00 CST 2021
     */
    @Override
    public void copy(Object a) {
        Leaders castObject = (Leaders) a;
        this.id = castObject.id;
        this.label = castObject.label;
        this.endterm = castObject.endterm;
        this.active = castObject.active;
    }

    public String simpleName() {
        return "Leaders";
    }
}