package com.ritchey.choices.domain.chapel;


import java.io.Serializable;
import java.util.Date;

public class ScheduledEvent implements Reflect, Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scheduledEvent.id
     *
     * @mbggenerated Tue Sep 29 14:08:33 CDT 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scheduledEvent.event
     *
     * @mbggenerated Tue Sep 29 14:08:33 CDT 2020
     */
    private Integer event;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scheduledEvent.starttime
     *
     * @mbggenerated Tue Sep 29 14:08:33 CDT 2020
     */
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scheduledEvent.endtime
     *
     * @mbggenerated Tue Sep 29 14:08:33 CDT 2020
     */
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scheduledEvent.template
     *
     * @mbggenerated Tue Sep 29 14:08:33 CDT 2020
     */
    private String template;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scheduledEvent.recordTardy
     *
     * @mbggenerated Tue Sep 29 14:08:33 CDT 2020
     */
    private Boolean recordtardy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scheduledEvent.recordLate
     *
     * @mbggenerated Tue Sep 29 14:08:33 CDT 2020
     */
    private Boolean recordlate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scheduledEvent.allcredit
     *
     * @mbggenerated Tue Sep 29 14:08:33 CDT 2020
     */
    private Boolean allcredit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scheduledEvent.split
     *
     * @mbggenerated Tue Sep 29 14:08:33 CDT 2020
     */
    private Boolean split;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scheduledEvent.splitByInstructor
     *
     * @mbggenerated Tue Sep 29 14:08:33 CDT 2020
     */
    private Boolean splitbyinstructor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table scheduledEvent
     *
     * @mbggenerated Tue Sep 29 14:08:33 CDT 2020
     */
    private static final long serialVersionUID = 20200929140833L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduledEvent.id
     *
     * @return the value of scheduledEvent.id
     *
     * @mbggenerated Tue Sep 29 14:08:33 CDT 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduledEvent.id
     *
     * @param id the value for scheduledEvent.id
     *
     * @mbggenerated Tue Sep 29 14:08:33 CDT 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduledEvent.event
     *
     * @return the value of scheduledEvent.event
     *
     * @mbggenerated Tue Sep 29 14:08:33 CDT 2020
     */
    public Integer getEvent() {
        return event;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduledEvent.event
     *
     * @param event the value for scheduledEvent.event
     *
     * @mbggenerated Tue Sep 29 14:08:33 CDT 2020
     */
    public void setEvent(Integer event) {
        this.event = event;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduledEvent.starttime
     *
     * @return the value of scheduledEvent.starttime
     *
     * @mbggenerated Tue Sep 29 14:08:33 CDT 2020
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduledEvent.starttime
     *
     * @param starttime the value for scheduledEvent.starttime
     *
     * @mbggenerated Tue Sep 29 14:08:33 CDT 2020
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduledEvent.endtime
     *
     * @return the value of scheduledEvent.endtime
     *
     * @mbggenerated Tue Sep 29 14:08:33 CDT 2020
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduledEvent.endtime
     *
     * @param endtime the value for scheduledEvent.endtime
     *
     * @mbggenerated Tue Sep 29 14:08:33 CDT 2020
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduledEvent.template
     *
     * @return the value of scheduledEvent.template
     *
     * @mbggenerated Tue Sep 29 14:08:33 CDT 2020
     */
    public String getTemplate() {
        return template;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduledEvent.template
     *
     * @param template the value for scheduledEvent.template
     *
     * @mbggenerated Tue Sep 29 14:08:33 CDT 2020
     */
    public void setTemplate(String template) {
        this.template = template == null ? null : template.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduledEvent.recordTardy
     *
     * @return the value of scheduledEvent.recordTardy
     *
     * @mbggenerated Tue Sep 29 14:08:33 CDT 2020
     */
    public Boolean getRecordtardy() {
        return recordtardy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduledEvent.recordTardy
     *
     * @param recordtardy the value for scheduledEvent.recordTardy
     *
     * @mbggenerated Tue Sep 29 14:08:33 CDT 2020
     */
    public void setRecordtardy(Boolean recordtardy) {
        this.recordtardy = recordtardy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduledEvent.recordLate
     *
     * @return the value of scheduledEvent.recordLate
     *
     * @mbggenerated Tue Sep 29 14:08:33 CDT 2020
     */
    public Boolean getRecordlate() {
        return recordlate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduledEvent.recordLate
     *
     * @param recordlate the value for scheduledEvent.recordLate
     *
     * @mbggenerated Tue Sep 29 14:08:33 CDT 2020
     */
    public void setRecordlate(Boolean recordlate) {
        this.recordlate = recordlate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduledEvent.allcredit
     *
     * @return the value of scheduledEvent.allcredit
     *
     * @mbggenerated Tue Sep 29 14:08:33 CDT 2020
     */
    public Boolean getAllcredit() {
        return allcredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduledEvent.allcredit
     *
     * @param allcredit the value for scheduledEvent.allcredit
     *
     * @mbggenerated Tue Sep 29 14:08:33 CDT 2020
     */
    public void setAllcredit(Boolean allcredit) {
        this.allcredit = allcredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduledEvent.split
     *
     * @return the value of scheduledEvent.split
     *
     * @mbggenerated Tue Sep 29 14:08:33 CDT 2020
     */
    public Boolean getSplit() {
        return split;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduledEvent.split
     *
     * @param split the value for scheduledEvent.split
     *
     * @mbggenerated Tue Sep 29 14:08:33 CDT 2020
     */
    public void setSplit(Boolean split) {
        this.split = split;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduledEvent.splitByInstructor
     *
     * @return the value of scheduledEvent.splitByInstructor
     *
     * @mbggenerated Tue Sep 29 14:08:33 CDT 2020
     */
    public Boolean getSplitbyinstructor() {
        return splitbyinstructor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduledEvent.splitByInstructor
     *
     * @param splitbyinstructor the value for scheduledEvent.splitByInstructor
     *
     * @mbggenerated Tue Sep 29 14:08:33 CDT 2020
     */
    public void setSplitbyinstructor(Boolean splitbyinstructor) {
        this.splitbyinstructor = splitbyinstructor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduledEvent
     *
     * @mbggenerated Tue Sep 29 14:08:33 CDT 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getName());
        sb.append("[");
        sb.append("Hash = ").append(hashCode());
        sb.append(",id=").append(id);
        sb.append(",event=").append(event);
        sb.append(",starttime=").append(starttime);
        sb.append(",endtime=").append(endtime);
        sb.append(",template=").append(template);
        sb.append(",recordtardy=").append(recordtardy);
        sb.append(",recordlate=").append(recordlate);
        sb.append(",allcredit=").append(allcredit);
        sb.append(",split=").append(split);
        sb.append(",splitbyinstructor=").append(splitbyinstructor);
        sb.append(",serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduledEvent
     *
     * @mbggenerated Tue Sep 29 14:08:33 CDT 2020
     */
    public String[] listFields() {
        return new String[]{"id","event","starttime","endtime","template","recordtardy","recordlate","allcredit","split","splitbyinstructor"};
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduledEvent
     *
     * @mbggenerated Tue Sep 29 14:08:33 CDT 2020
     */
    @Override
    public Object get(String name) {
        if (name.equals("id")) return id;
        if (name.equals("event")) return event;
        if (name.equals("starttime")) return starttime;
        if (name.equals("endtime")) return endtime;
        if (name.equals("template")) return template;
        if (name.equals("recordtardy")) return recordtardy;
        if (name.equals("recordlate")) return recordlate;
        if (name.equals("allcredit")) return allcredit;
        if (name.equals("split")) return split;
        if (name.equals("splitbyinstructor")) return splitbyinstructor;
        return null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduledEvent
     *
     * @mbggenerated Tue Sep 29 14:08:33 CDT 2020
     */
    @Override
    public void set(String name, Object value) {
        if (name.equals("id")) id = value==null?null:(java.lang.Integer) value;
        if (name.equals("event")) event = value==null?null:(java.lang.Integer) value;
        if (name.equals("starttime")) starttime = value==null?null:(java.util.Date) value;
        if (name.equals("endtime")) endtime = value==null?null:(java.util.Date) value;
        if (name.equals("template")) template = value==null?null:(java.lang.String) value;
        if (name.equals("recordtardy")) recordtardy = value==null?null:(java.lang.Boolean) value;
        if (name.equals("recordlate")) recordlate = value==null?null:(java.lang.Boolean) value;
        if (name.equals("allcredit")) allcredit = value==null?null:(java.lang.Boolean) value;
        if (name.equals("split")) split = value==null?null:(java.lang.Boolean) value;
        if (name.equals("splitbyinstructor")) splitbyinstructor = value==null?null:(java.lang.Boolean) value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduledEvent
     *
     * @mbggenerated Tue Sep 29 14:08:33 CDT 2020
     */
    @Override
    public void copy(Object a) {
        ScheduledEvent castObject = (ScheduledEvent) a;
        this.id = castObject.id;
        this.event = castObject.event;
        this.starttime = castObject.starttime;
        this.endtime = castObject.endtime;
        this.template = castObject.template;
        this.recordtardy = castObject.recordtardy;
        this.recordlate = castObject.recordlate;
        this.allcredit = castObject.allcredit;
        this.split = castObject.split;
        this.splitbyinstructor = castObject.splitbyinstructor;
    }

    public String simpleName() {
        return "ScheduledEvent";
    }
}