package com.ritchey.choices.domain.chapel;

import java.io.Serializable;
import java.util.Date;

public class SplitByLeader implements Reflect, Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column split_by_leader.id
     *
     * @mbggenerated Thu Sep 24 11:16:51 CDT 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column split_by_leader.personId
     *
     * @mbggenerated Thu Sep 24 11:16:51 CDT 2020
     */
    private Integer personid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column split_by_leader.endTerm
     *
     * @mbggenerated Thu Sep 24 11:16:51 CDT 2020
     */
    private Date endterm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column split_by_leader.leaderId
     *
     * @mbggenerated Thu Sep 24 11:16:51 CDT 2020
     */
    private Integer leaderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table split_by_leader
     *
     * @mbggenerated Thu Sep 24 11:16:51 CDT 2020
     */
    private static final long serialVersionUID = 20200924111651L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column split_by_leader.id
     *
     * @return the value of split_by_leader.id
     *
     * @mbggenerated Thu Sep 24 11:16:51 CDT 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column split_by_leader.id
     *
     * @param id the value for split_by_leader.id
     *
     * @mbggenerated Thu Sep 24 11:16:51 CDT 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column split_by_leader.personId
     *
     * @return the value of split_by_leader.personId
     *
     * @mbggenerated Thu Sep 24 11:16:51 CDT 2020
     */
    public Integer getPersonid() {
        return personid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column split_by_leader.personId
     *
     * @param personid the value for split_by_leader.personId
     *
     * @mbggenerated Thu Sep 24 11:16:51 CDT 2020
     */
    public void setPersonid(Integer personid) {
        this.personid = personid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column split_by_leader.endTerm
     *
     * @return the value of split_by_leader.endTerm
     *
     * @mbggenerated Thu Sep 24 11:16:51 CDT 2020
     */
    public Date getEndterm() {
        return endterm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column split_by_leader.endTerm
     *
     * @param endterm the value for split_by_leader.endTerm
     *
     * @mbggenerated Thu Sep 24 11:16:51 CDT 2020
     */
    public void setEndterm(Date endterm) {
        this.endterm = endterm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column split_by_leader.leaderId
     *
     * @return the value of split_by_leader.leaderId
     *
     * @mbggenerated Thu Sep 24 11:16:51 CDT 2020
     */
    public Integer getLeaderid() {
        return leaderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column split_by_leader.leaderId
     *
     * @param leaderid the value for split_by_leader.leaderId
     *
     * @mbggenerated Thu Sep 24 11:16:51 CDT 2020
     */
    public void setLeaderid(Integer leaderid) {
        this.leaderid = leaderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table split_by_leader
     *
     * @mbggenerated Thu Sep 24 11:16:51 CDT 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getName());
        sb.append("[");
        sb.append("Hash = ").append(hashCode());
        sb.append(",id=").append(id);
        sb.append(",personid=").append(personid);
        sb.append(",endterm=").append(endterm);
        sb.append(",leaderid=").append(leaderid);
        sb.append(",serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table split_by_leader
     *
     * @mbggenerated Thu Sep 24 11:16:51 CDT 2020
     */

    public String[] listFields() {
        return new String[]{"id","personid","endterm","leaderid"};
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table split_by_leader
     *
     * @mbggenerated Thu Sep 24 11:16:51 CDT 2020
     */
    @Override
    public Object get(String name) {
        if (name.equals("id")) return id;
        if (name.equals("personid")) return personid;
        if (name.equals("endterm")) return endterm;
        if (name.equals("leaderid")) return leaderid;
        return null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table split_by_leader
     *
     * @mbggenerated Thu Sep 24 11:16:51 CDT 2020
     */
    @Override
    public void set(String name, Object value) {
        if (name.equals("id")) id = value==null?null:(java.lang.Integer) value;
        if (name.equals("personid")) personid = value==null?null:(java.lang.Integer) value;
        if (name.equals("endterm")) endterm = value==null?null:(java.util.Date) value;
        if (name.equals("leaderid")) leaderid = value==null?null:(java.lang.Integer) value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table split_by_leader
     *
     * @mbggenerated Thu Sep 24 11:16:51 CDT 2020
     */
    @Override
    public void copy(Object a) {
        SplitByLeader castObject = (SplitByLeader) a;
        this.id = castObject.id;
        this.personid = castObject.personid;
        this.endterm = castObject.endterm;
        this.leaderid = castObject.leaderid;
    }

    public String simpleName() {
        return "SplitByLeader";
    }
}