package com.ritchey.choices.mapper.chapel;

import java.util.Date;
import java.util.List;
import java.util.Map;

import org.apache.commons.collections4.map.CaseInsensitiveMap;
import org.apache.ibatis.annotations.Param;

import com.ritchey.choices.domain.chapel.Leaders;
import com.ritchey.choices.domain.chapel.LeadersExample;

public interface LeadersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leaders
     *
     * @mbggenerated Thu Jan 14 11:34:00 CST 2021
     */
    int countByExample(LeadersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leaders
     *
     * @mbggenerated Thu Jan 14 11:34:00 CST 2021
     */
    int deleteByExample(LeadersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leaders
     *
     * @mbggenerated Thu Jan 14 11:34:00 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leaders
     *
     * @mbggenerated Thu Jan 14 11:34:00 CST 2021
     */
    int insert(Leaders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leaders
     *
     * @mbggenerated Thu Jan 14 11:34:00 CST 2021
     */
    int insertSelective(Leaders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leaders
     *
     * @mbggenerated Thu Jan 14 11:34:00 CST 2021
     */
    List<Leaders> selectByExample(LeadersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leaders
     *
     * @mbggenerated Thu Jan 14 11:34:00 CST 2021
     */
    Leaders selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leaders
     *
     * @mbggenerated Thu Jan 14 11:34:00 CST 2021
     */
    int updateByExampleSelective(@Param("record") Leaders record, @Param("example") LeadersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leaders
     *
     * @mbggenerated Thu Jan 14 11:34:00 CST 2021
     */
    int updateByExample(@Param("record") Leaders record, @Param("example") LeadersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leaders
     *
     * @mbggenerated Thu Jan 14 11:34:00 CST 2021
     */
    int updateByPrimaryKeySelective(Leaders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leaders
     *
     * @mbggenerated Thu Jan 14 11:34:00 CST 2021
     */
    int updateByPrimaryKey(Leaders record);

    String getExportColumns(@Param("startterm") Date startterm, @Param("endterm") Date endterm);
    List<Map> export(@Param("startterm") Date startterm, @Param("endterm") Date endterm, @Param("columns") String columns);
    
    List<Map> selectActiveLeaders(@Param("maxSeatCount") Integer maxSeatCount);
    
    Integer selectIsSplitByMentor();

}