package com.ritchey.choices.mapper.chapel;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.ritchey.choices.domain.chapel.Leaders;
import com.ritchey.choices.domain.chapel.SplitByLeader;
import com.ritchey.choices.domain.chapel.SplitByLeaderExample;

public interface SplitByLeaderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table split_by_leader
     *
     * @mbggenerated Thu Sep 24 11:16:51 CDT 2020
     */
    int countByExample(SplitByLeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table split_by_leader
     *
     * @mbggenerated Thu Sep 24 11:16:51 CDT 2020
     */
    int deleteByExample(SplitByLeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table split_by_leader
     *
     * @mbggenerated Thu Sep 24 11:16:51 CDT 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table split_by_leader
     *
     * @mbggenerated Thu Sep 24 11:16:51 CDT 2020
     */
    int insert(SplitByLeader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table split_by_leader
     *
     * @mbggenerated Thu Sep 24 11:16:51 CDT 2020
     */
    int insertSelective(SplitByLeader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table split_by_leader
     *
     * @mbggenerated Thu Sep 24 11:16:51 CDT 2020
     */
    List<SplitByLeader> selectByExample(SplitByLeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table split_by_leader
     *
     * @mbggenerated Thu Sep 24 11:16:51 CDT 2020
     */
    SplitByLeader selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table split_by_leader
     *
     * @mbggenerated Thu Sep 24 11:16:51 CDT 2020
     */
    int updateByExampleSelective(@Param("record") SplitByLeader record, @Param("example") SplitByLeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table split_by_leader
     *
     * @mbggenerated Thu Sep 24 11:16:51 CDT 2020
     */
    int updateByExample(@Param("record") SplitByLeader record, @Param("example") SplitByLeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table split_by_leader
     *
     * @mbggenerated Thu Sep 24 11:16:51 CDT 2020
     */
    int updateByPrimaryKeySelective(SplitByLeader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table split_by_leader
     *
     * @mbggenerated Thu Sep 24 11:16:51 CDT 2020
     */
    int updateByPrimaryKey(SplitByLeader record);
    
    int updateByPeopleIdAndLabel(@Param("peopleId") String peopleId, @Param("label") String label);
    int insertByPeopleIdAndLabel(@Param("peopleId") String peopleId, @Param("label") String label);
    
    List<String> selectLeaders(String string);
    List<Leaders> selectLeadersList(@Param("filter") String filter, @Param("active") Boolean activeOnly, RowBounds r);
    Integer selectLeadersListCount(@Param("filter") String filter, @Param("active") Boolean activeOnly);
}